### ISSUE TITLE
Kalamata 0.1.3 on npm is outdated (Bookshelf version dependency)

### ISSUE THREAD

**Issue by nabilfreeman** [mikec/kalamata#5]
This pull request: https://github.com/mikec/kalamata/pull/4

Updated Kalamata's Bookshelf dependency to a modern version (`^0.10`), but didn't come with a version bump.

npm hosts the same version, but with an older package.json - it lists Bookshelf `^0.7.7` as a peer dependency. This is causing some issues for people who would like to use Kalamata via npm, but with a newer version of Bookshelf. A side effect of this is also failed AWS Elastic Beanstalk deployments.

@mikec, if you want to fix this issue you need to run `npm publish` 📈

**Comment by nabilfreeman** [comment]
For anybody coming here to fix unmet peer dependency errors in Bookshelf, you can point your `package.json` entry for Kalamata to the git repo, `https://github.com/mikec/kalamata/pull/4`.

**Comment by mikec** [comment]
@nabilfreeman thanks! bumped to v.0.1.4 https://github.com/mikec/kalamata/commit/8c59b24de26c7c947c7c3acbf1ed7c1906b6d41e and published to npm

**Comment by nabilfreeman** [comment]
@mikec you legend! thanks for a speedy fix. Btw, Kalamata is perfect for our needs so far - good job 😁

**Comment by mikec** [comment]
@nabilfreeman dude you just made my night, glad it's working well for you!
